# Generated by Django 2.2.13 on 2021-03-30 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesClass', to='accounts.Class')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRealization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.Activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.Student')),
            ],
            options={
                'db_table': 'activity_answer',
            },
        ),
        migrations.CreateModel(
            name='ActivityRealizationTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ActivityRealizationTeacher',
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(verbose_name='letter')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('is_openQuestion', models.BooleanField(default=False)),
                ('is_multipleChoiceQuestion', models.BooleanField(default=False)),
                ('link_multimedia', models.TextField(blank=True, null=True, verbose_name='link multimedia')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taks_location', to='location.Location')),
                ('taks', models.ManyToManyField(to='content.Question', verbose_name='question')),
            ],
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestionOfCorrectAnswer', models.TextField(blank=True, null=True, verbose_name='description')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openquestion', to='content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ManyToManyField(to='content.Alternative', verbose_name='alternative')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multipleChoiceQuestion', to='content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='accounts.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='description')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('activityRealization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerTeacher', to='content.ActivityRealizationTeacher')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerTeacher', to='content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='description')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('activityRealization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='content.ActivityRealization')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer', to='content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesTeacher', to='accounts.ClassTeacher')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitiesTeacher', to='content.Content')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesTeacher', to='accounts.CourseTeacher')),
                ('taks', models.ManyToManyField(to='content.Task', verbose_name='taks')),
            ],
        ),
        migrations.AddField(
            model_name='activityrealizationteacher',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivityRealizationTeacher', to='content.ActivityTeacher'),
        ),
        migrations.AddField(
            model_name='activityrealizationteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivityRealizationTeacher', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='activity',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitiesContent', to='content.Content'),
        ),
        migrations.AddField(
            model_name='activity',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesCourse', to='accounts.Course'),
        ),
        migrations.AddField(
            model_name='activity',
            name='taks',
            field=models.ManyToManyField(to='content.Task', verbose_name='taks'),
        ),
    ]
