# Generated by Django 2.2.13 on 2021-04-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerteacher',
            name='score',
        ),
        migrations.CreateModel(
            name='AnswerTeacherMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='description')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('activityRealization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerTeacherMultipleChoice', to='content.ActivityRealizationTeacher')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerTeacherMultipleChoice', to='content.Alternative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerTeacherMultipleChoice', to='content.Question')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerMultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='description')),
                ('activityRealization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerMultipleChoice', to='content.ActivityRealization')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerMultipleChoice', to='content.Alternative')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AnswerMultipleChoice', to='content.Question')),
            ],
        ),
    ]
