# Generated by Django 2.2.13 on 2021-04-22 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210422_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerteachermultiplechoice',
            name='score',
        ),
    ]
