# Generated by Django 2.2.13 on 2021-05-05 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0004_remove_answerteachermultiplechoice_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='belongs_to_an_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='activityteacher',
            name='belongs_to_an_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activityteacher',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitiesTeacher', to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='content',
            name='belongs_to_an_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='accounts.Teacher'),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='accounts.Teacher'),
        ),
    ]
