# Generated by Django 2.2.13 on 2021-05-05 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210505_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taks',
            new_name='questions',
        ),
        migrations.AddField(
            model_name='alternative',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alternative', to='content.Question'),
        ),
    ]
