# Generated by Django 2.2.13 on 2021-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
