# Generated by Django 2.2.13 on 2021-05-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20210517_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityteacher',
            name='taks',
        ),
        migrations.AddField(
            model_name='activityteacher',
            name='tasks',
            field=models.ManyToManyField(to='content.Task', verbose_name='tasks'),
        ),
    ]
