# Generated by Django 2.2.13 on 2021-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210530_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_alternative',
            field=models.TextField(blank=True, null=True),
        ),
    ]
